[package]
name = "gbemu-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.11.0"
winit = "0.27.5"
minifb = "0.23.0"
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
parse_int = "0.6.0"
